[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "cryptography>=46.0.3",
    "dnspython>=2.8.0",
    "python-telegram-bot>=22.5",
    "requests>=2.32.5",
]
