[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=25.1.0",
    "colorama>=0.4.6",
    "httpx>=0.28.1",
    "rich>=14.2.0",
]
